### ISSUE TITLE
正式训练出现问题

### ISSUE THREAD

**Issue by wangtao1321** [yongyehuang/zhihu-text-classification#1]
您好，我在跑wd_1_1_cnn_concat模型时，数据预处理和测试都没问题，但是正式运行时，遇到了一个非常大的问题，就是训练一段时间后会自动把整个zhihu-text-classification文件夹删除，产生如下报错：
IOError：[Errno 2]No such file or directory:'../../data/wd-data/data_train/6317.npz'
第一次出现这个错误，我还以为是谁把我的文件夹删了，但是第二次重新训练又出现了同样的情况，整个zhihu-text-classification文件夹自己被删除。
请问您在实验过程中有遇到过这样的问题吗？

**Comment by yongyehuang** [comment]
@wangtao1321 你好，感谢你的提问。针对这个问题我重新跑了一下代码，**没有遇到你这样的问题**。在模型训练的过程中，只有  **shutil.rmtree() 这个函数会删除整个文件夹**，在重新训练模型的过程中会删除 summary 目录，但是不会删除整个大目录。所以你某个地方改过文件的目录？你可以查找一下有没有在什么地方用了 **shutil.rmtree()** 导致删除文件夹。

**Comment by wangtao1321** [comment]
@yongyehuang ，感谢您的回答，还有一个问题是，目前这个版本的wd_2_hcnn模型代码中，train.py部分似乎有一些问题，调用的还是TextCNN这个类，而不是HCNN类，并且直接改为HCNN后会报错

**Comment by yongyehuang** [comment]
@wangtao1321 非常感谢指出错误，我已经上传改正的代码。之前改成 HCNN 后还会报错是因为 HCNN 用的分层结构，需要使用划分句子的数据，所以把原代码中 data_path 修改就好了。

**Comment by wangtao1321** [comment]
@yongyehuang ，请问您有没有在TextCNN模型上尝试过多加几层卷积，我之前觉得这种复杂多分类问题将模型变深后应该可以提高点效果，但是加了几层cnn后发现f1值反倒下降了不少，不知道是我卷积加得有问题还是继续变深模型效果的确会下降。。（第一个textcnn模型加了一层和原来那层相同结构的卷积，f1下降了0.03左右）

**Comment by WLCOOLONGS** [comment]
您好，在多分类里面存在数据不均衡问题，那在知乎提供的这份多标签分类的数据里面存不存在数据不均衡这样的问题呢，刚刚开始看这种多标签的相关代码，不太清楚这个问题，还是说在文本预处理的时候进行相关的处理了呢（还是直接拿来训练就好），期待回答，谢谢

**Comment by yongyehuang** [comment]
@WangLianChen 你好，在知乎这次比赛提供的数据中，我统计了一下，没有存在严重的数据不均衡问题，所以不需要进行相关的处理。如果是其他数据集存在严重的数据不均衡的话可能需要考虑做些处理。

**Comment by WLCOOLONGS** [comment]
@yongyehuang 谢谢
