### ISSUE TITLE
task_specific_attention

### ISSUE THREAD

**Issue by coderApes** [yongyehuang/zhihu-text-classification#4]
Hi， 你好，
       看了你的代码感觉收获很大，非常感谢。我有一个问题不是很明白：在Bi-gru模型中，task_specific_attention  这个一步骤是添加注意力机制吗？我看不太明白，能不能给个论文或者blog链接，谢谢！

**Comment by yongyehuang** [comment]
@coderApes 你可以看看这2篇论文，主要看看 【1】就够了。
-  [【1】《Hierarchical Attention Networks for Document Classification》](https://github.com/yongyehuang/zhihu-text-classification/blob/master/doc/reference/2016-HAN-N16-Hierarchical%20Attention%20Networks%20for%20Document%20Classification.pdf)
-  [【2】《Neural Machine Translation by Jointly Learning to Align and Translate》](https://arxiv.org/abs/1409.0473) 
【1】就是做的文本分类，【2】是比较早的提出这种注意力机制方式的论文。

**Comment by coderApes** [comment]
多谢，我仔细看一下这两篇论文
