### ISSUE TITLE
请问切割成句子时，切割符号是哪里来的呢？

### ISSUE THREAD

**Issue by kingbase** [yongyehuang/zhihu-text-classification#5]
在这里: https://github.com/yongyehuang/zhihu-text-classification/blob/master/data_helpers.py#L236
有个疑问，请问这几个值是如何得来的？
谢谢。

**Comment by yongyehuang** [comment]
@kingbase 词频统计+肉眼分析+猜测

**Comment by kingbase** [comment]
受教，厉害了！
